### ISSUE TITLE
Can't compile. Missing files

### ISSUE THREAD

**Issue by tgodtaylor** [citizenfx/fivem#1014]
\fivem\ext\native-doc-tooling\node_modules\ffi-napi\lib\dynamic_library.js:75
    throw new Error('Dynamic Linking Error: ' + err);
    ^

Error: Dynamic Linking Error: Win32 error 193
    at new DynamicLibrary (\fivem\ext\native-doc-tooling\node_modules\ffi-napi\lib\dynamic_library.js:75:11)
    at new Library (fivem\ext\native-doc-tooling\node_modules\ffi-napi\lib\library.js:47:10)
    at Object.<anonymous> (fivem\ext\native-doc-tooling\node_modules\libclang\lib\dynamic_clang.js:946:20)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (fivem\ext\native-doc-tooling\node_modules\libclang\lib\cursor.js:24:9)
fivem\ext\native-doc-tooling\node_modules\ffi-napi\lib\dynamic_library.js:75
    throw new Error('Dynamic Linking Error: ' + err);

**Comment by blattersturm** [comment]
This isn't a support section.

Also, use 64-bit Node.js, not 32-bit.
