### ISSUE TITLE
Linux build broke: "module 'xpidl.xpidlyacc' has no attribute '_tabversion'"

### ISSUE THREAD

**Issue by blattersturm** [citizenfx/fivem#1371]
Linux build might have broken, likely due to Alpine/PyPI package updates:

```
Traceback (most recent call last):
  File "/src/code/tools/idl/header.py", line 10, in <module>
    header.main()
  File "/src/code/tools/idl/xpidl/header.py", line 537, in main
    p = xpidl.IDLParser(outputdir=options.cachedir)
  File "/src/code/tools/idl/xpidl/xpidl.py", line 1434, in __init__
    self.parser = yacc.yacc(module=self,
  File "/usr/lib/python3.10/site-packages/ply/yacc.py", line 3293, in yacc
    read_signature = lr.read_table(tabmodule)
  File "/usr/lib/python3.10/site-packages/ply/yacc.py", line 1987, in read_table
    if parsetab._tabversion != __tabversion__:
AttributeError: module 'xpidl.xpidlyacc' has no attribute '_tabversion'
```

**Comment by blattersturm** [comment]
This _may_ also affect fresh builds on other systems.

**Comment by blattersturm** [comment]
Turns out this was an intermittent issue only - might be a failure earlier didn't get propagated.
